/* CUSTOMER DATA - generated by Royal Nikah Cards Admin Panel. */
window.WEDDING_CONFIG = {
  customerSlug: "maaz-khan-khatija-quraishi",
  groom: { name: "Maaz Khan", father: "MD.Sajid Khan" },
  bride: { name: "Khatija Quraishi", father: "Haneef Ahmed Quraishi" },
  initials: { groom: "M", bride: "K" },
  familySurname: "Khan",
  nikah: { date: "2026-11-01", countdownDateTime: "2026-11-01T17:00:00+05:30", time: "After Namaz-e-Asar", venue: "Jama Masjid", address: "Buddi Lane, Aurangabad, Maharashtra, 431001", map: "https://maps.app.goo.gl/GSrPN58Rn4TR9QVG7" },
  walima: { date: "2026-11-02", time: "08:00 PM", venue: "Abdul Karim Function Hall", address: "Near K K Petrol Pump, Babar Colony, Kat Kat Gate, Jaswantpura, Aurangabad, Maharashtra 431001", map: "https://maps.app.goo.gl/ydozRH1cWUnbJgCq8" },
  contact: { phone: "9527468673" },
  calendar: { title: "Maaz's Wedding", durationHours: 3 },
  assets: {"welcomeBackground": "assets/welcome-background.jpg", "invitationBackground": "assets/invitation-background.png", "couple": "assets/bride-groom.png", "nikahVenue": "assets/nikah-venue.jpg", "walimaVenue": "assets/walima-venue.jpg", "music": "assets/Backgroundmusic.mp3"}
};
